### ISSUE TITLE
Near/Far Pointer Mismatch

### ISSUE THREAD

**Issue by sidwarkd** [ms-iot/virtual-shields-arduino#16]
in `VirtualShield::sendFlashStringOnSerial()` (around line 788) the `for` loop checks for a far pointer and the next line does a `pgm_read_byte_near`.

**Comment by JimGaleForce** [comment]
by-design... this was the only way this worked. the pgm_read_byte_far didn't work at all here. bug in arduino code? not sure.

**Comment by zfields** [comment]
the signature for `strlen_PF()` is `size_t  strlen_PF (uint_farptr_t src)`, which is probably where the requirement for the `uint_farptr_t` is coming from.
