### ISSUE TITLE
Can't pair on USB.

### ISSUE THREAD

**Issue by Brainer189** [ms-iot/virtual-shields-arduino#36]
I've downloaded the app, installed the libraries, but the app says no paired devices found.

**Comment by ooeygui** [comment]
Did you install the firmware on the Arduino? 
What bluetooth module are you using?

**Comment by ooeygui** [comment]
Sorry for the delay in responding.
Which arduino are you using?

**Comment by Brainer189** [comment]
I have used an Arduino Uno. I havent used a bluetooth module. It doesnt
works without it?

2016-12-07 5:39 GMT+02:00 Lou Amadio <notifications@github.com>:

**Comment by IoTGirl** [comment]
Hi Brainer,
There is a discussion on a similar topic on the forums. Is this what you are attempting? [https://social.msdn.microsoft.com/Forums/en-US/1db42e25-79bf-4f50-a899-4948ce266bc1/windows-virtual-shield-connection-via-usb-does-not-work?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/1db42e25-79bf-4f50-a899-4948ce266bc1/windows-virtual-shield-connection-via-usb-does-not-work?forum=WindowsIoT)
Sincerely,
IoTGirl

**Comment by IoTGirl** [comment]
Closing as stale - no follow up for months.  Others have had success downloading the source and using their own copy off the connection app rather than the one from the store.
