### ISSUE TITLE
Is WiFi or Ethernet not supported?

### ISSUE THREAD

**Issue by ChuckBell** [ms-iot/virtual-shields-arduino#37]
Although the MS documentation states we can use Wifi (network) connections and the UWP app has a selection for such, there are no examples or explanations of how to setup the Arduino sketch to use networking. Is this not supported? Is it a future edition? If it is supported, how about throwing us a bone and put an example in the code?

**Comment by IoTGirl** [comment]
Hi @ChuckBell,
There is a video at https://blogs.windows.com/buildingapps/2016/01/27/what-is-windows-virtual-shields-for-arduino-and-what-can-it-do/#Chel1GrDG8vybGoi.97 showing the use of the companion application to connect.
Sincerely,
IoTGirl
