### ISSUE TITLE
Local media playback?

### ISSUE THREAD

**Issue by HanJammer** [ms-iot/virtual-shields-arduino#39]
I'm creating a talking mobile robot. Since I deployed Virtual Shields app via Visual Studio everything work flawlessly, unfortunatelly I don't know if it's possible to play local audio/video files using Media.h library. In the examples I only found the remote media file playback, it works but, it is next to useless in my aplication (it takes time to download sound file and what's worse - this time varies depending on the network speed etc, it also requires the phone is connected to the Internet. Generally it messes up the program - one sample starts playing in the middle of another sample etc). For speech I can use Text-to-Speech Speech.h library which works allright, but in this project I'm also using some other sounds (beeps etc)...

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.
