### ISSUE TITLE
serial 9600 issue not printing screen

### ISSUE THREAD

**Issue by endricott** [ms-iot/virtual-shields-arduino#42]
my bt hc-05 module Baund(9600) connects but no text on windows virtual shield, i added Serial.begin(9600); shield.begin(); now i'm able to get text if i connect serial port 13 first on vs 2015 or disconnect it... but standalone andruino not sending data to  win virtual shield without first connect to port, wenn i'm testing Hello World Speech eventing it dosnt listening or not recognizing. maybe somebody knows how i could solve it? how to change shield.begin() to shield.beginn(9600?) adding 9600 doesnt change baund?

**Comment by endricott** [comment]
Wmobile os v 1703

**Comment by saraclay** [comment]
Hi @endricott - we are asking if people could file their issues over in our documentation repo here: https://github.com/MicrosoftDocs/windows-iotcore-docs so I am closing this for now. Thank you.
